---
version: '2'
plugins:
  bundler-audit:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  # editorconfig:
  #   enabled: true
  #   channel: beta
  #   config:
  #     editorconfig: .editorconfig
  flog:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
      enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-54
exclude_patterns:
  - Gemfile
  - "*.gemspec"
  - Appraisals
  - spec/**/*.rb
  - gemfiles/**/*
  - rails_example/**/*
  - redis/**/*
  - tmp/**/*

