---
version: '2'
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  flog:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
    config:
      file: .reek.yml
  rubocop:
    enabled: true
    channel: rubocop-0-70
    config:
      file: .rubocop.yml

exclude_patterns:
  - "Gemfile"
  - "*.gemspec"
  - "Appraisals"
  - "gemfiles/"
  - "my_app/"
  - "tmp/"
  - "spec/"
  - "assets/"
  - "lib/sidekiq/logging.rb"
  - "spec/support/sidekiq_unique_jobs/testing.rb"
