---
exclude_paths:
  - examples
  - gemfiles
  - lib/sidekiq
  - lib/sidekiq_unique_jobs/lua
  - myapp
  - spec
  - tmp
  - vendor/bundle
detectors:
  BooleanParameter:
    exclude:
      - SidekiqUniqueJobs::Cli#self.banner
      - SidekiqUniqueJobs::Redis
      - SidekiqUniqueJobs::Lock#locked_jids
  ControlParameter:
    exclude:
      - Sidekiq::JobSet::UniqueExtension#delete_by_value
      - Sidekiq::ScheduledSet::UniqueExtension#delete
      - SidekiqUniqueJobs::Orphans::RubyReaper#active?
      - SidekiqUniqueJobs::Redis::Hash#entries
  DataClump:
    enabled: true
    exclude:
      - SidekiqUniqueJobs::DeleteOrphan
      - SidekiqUniqueJobs::Redis
  DuplicateMethodCall:
    exclude:
      - Sidekiq#self.use_options
      - SidekiqUniqueJobs#toggle
      - SidekiqUniqueJobs::Lock#del
      - SidekiqUniqueJobs::Lock#lock
      - SidekiqUniqueJobs::Lock::WhileExecuting#execute
      - SidekiqUniqueJobs::Locksmith#enqueue
      - SidekiqUniqueJobs::Locksmith#lock_sync
      - SidekiqUniqueJobs::Locksmith#set_lock_info
      - SidekiqUniqueJobs::Locksmith#wait_for_primed_token
      - SidekiqUniqueJobs::OnConflict::Reschedule#call
      - SidekiqUniqueJobs::Orphans::RubyReaper#entries
      - SidekiqUniqueJobs::Profiler#self.stop
      - SidekiqUniqueJobs::Script::Caller#extract_args
      - SidekiqUniqueJobs::Timing#timed
      - SidekiqUniqueJobs::Web#self.registered
  FeatureEnvy:
    exclude:
      - SidekiqUniqueJobs::BatchDelete#batch_delete
      - SidekiqUniqueJobs::Digests#page
      - SidekiqUniqueJobs::Digests#page
      - SidekiqUniqueJobs::InvalidUniqueArguments#initialize
      - SidekiqUniqueJobs::InvalidWorker#initialize
      - SidekiqUniqueJobs::Logging#debug_item
      - SidekiqUniqueJobs::NotUniqueWorker#initialize
      - SidekiqUniqueJobs::OnConflict::Reject#push_to_deadset
      - SidekiqUniqueJobs::Orphans::RubyReaper#active?
      - SidekiqUniqueJobs::Orphans::RubyReaper#entries
      - SidekiqUniqueJobs::Redis::Entity#exist?
      - SidekiqUniqueJobs::SidekiqWorkerMethods#worker_class_constantize
      - SidekiqUniqueJobs::Web::Helpers#cparams
  IrresponsibleModule:
    enabled: true
  LongParameterList:
    enabled: true
    exclude:
      - Hash#slice
      - initialize
      - SidekiqUniqueJobs::Changelog#add
      - SidekiqUniqueJobs::Middleware#call
      - SidekiqUniqueJobs::Redis
      - SidekiqUniqueJobs::Script::Caller#call_script
      - SidekiqUniqueJobs::Script::Caller#do_call
  ManualDispatch:
    enabled: true
    exclude:
      - Hash#slice
      - Hash#slice!
      - SidekiqUniqueJobs::Logging#logger_respond_to_with_context?
      - SidekiqUniqueJobs::Server#self.configure
      - SidekiqUniqueJobs::OnConflict::Reject#deadset_kill?
      - SidekiqUniqueJobs::SidekiqWorkerMethods#worker_method_defined?
      - SidekiqUniqueJobs::Web::Helpers#redirect_to
      - SidekiqUniqueJobs::SidekiqWorkerMethods#after_unlock_hook
  MissingSafeMethod:
    exclude:
      - Array
  NilCheck:
    enabled: false
  NestedIterators:
    exclude:
      - SidekiqUniqueJobs::BatchDelete#batch_delete
      - SidekiqUniqueJobs::BatchDelete#keys_for_digest
      - SidekiqUniqueJobs::Changelog#entries
      - SidekiqUniqueJobs::Changelog#page
      - SidekiqUniqueJobs::Digests#page
      - SidekiqUniqueJobs::Locksmith#create_lock
      - SidekiqUniqueJobs::Middleware#self.configure_client
      - SidekiqUniqueJobs::Middleware#self.configure_server
      - SidekiqUniqueJobs::Orphans::RubyReaper#active?
      - SidekiqUniqueJobs::Orphans::RubyReaper#enqueued?
      - SidekiqUniqueJobs::UpgradeLocks#keys_for_digest
  RepeatedConditional:
    exclude:
      - SidekiqUniqueJobs::Locksmith
  TooManyConstants:
    exclude:
      - SidekiqUniqueJobs
  TooManyStatements:
    exclude:
      - Hash#slice
      - initialize
      - Sidekiq#self.use_options
      - SidekiqUniqueJobs#use_config
      - SidekiqUniqueJobs::BatchDelete#batch_delete
      - SidekiqUniqueJobs::Changelog#entries
      - SidekiqUniqueJobs::Changelog#page
      - SidekiqUniqueJobs::DeleteOrphans#find_orphans
      - SidekiqUniqueJobs::Digests#delete_by_pattern
      - SidekiqUniqueJobs::Digests#entries
      - SidekiqUniqueJobs::Digests#page
      - SidekiqUniqueJobs::Lock#lock
      - SidekiqUniqueJobs::Lock::WhileExecuting#execute
      - SidekiqUniqueJobs::LockArgs#filtered_args
      - SidekiqUniqueJobs::LockInfo#set
      - SidekiqUniqueJobs::Locksmith#enqueue
      - SidekiqUniqueJobs::Locksmith#lock
      - SidekiqUniqueJobs::Locksmith#lock_async
      - SidekiqUniqueJobs::Locksmith#lock_sync
      - SidekiqUniqueJobs::LockTTL#calculate
      - SidekiqUniqueJobs::Logging::Middleware#logging_context
      - SidekiqUniqueJobs::Middleware#call
      - SidekiqUniqueJobs::Server#self.configure
      - SidekiqUniqueJobs::Orphans::Manager#start
      - SidekiqUniqueJobs::Orphans::Manager#stop
      - SidekiqUniqueJobs::Orphans::RubyReaper#active?
      - SidekiqUniqueJobs::Orphans::RubyReaper#enqueued?
      - SidekiqUniqueJobs::Orphans::RubyReaper#entries
      - SidekiqUniqueJobs::Profiler#self.stop
      - SidekiqUniqueJobs::Script::Caller#call_script
      - SidekiqUniqueJobs::Script::Caller#extract_args
      - SidekiqUniqueJobs::SidekiqWorkerMethods#worker_class_constantize
      - SidekiqUniqueJobs::UpgradeLocks#call
      - SidekiqUniqueJobs::UpgradeLocks#upgrade_v6_lock
      - SidekiqUniqueJobs::Web#self.registered
  TooManyInstanceVariables:
    exclude:
      - SidekiqUniqueJobs::Key
      - SidekiqUniqueJobs::LockConfig
      - SidekiqUniqueJobs::Locksmith
      - SidekiqUniqueJobs::Lock::BaseLock
  TooManyMethods:
    exclude:
      - SidekiqUniqueJobs::Lock::BaseLock
      - SidekiqUniqueJobs::Locksmith
      - SidekiqUniqueJobs::Lock
      - SidekiqUniqueJobs::Orphans::Reaper
  UncommunicativeVariableName:
    exclude:
      - Hash#slice
  UncommunicativeParameterName:
    exclude:
      - SidekiqUniqueJobs::Redis
  UtilityFunction:
    enabled: false
