---
exclude_paths:
  - my_app
  - spec
  - tmp
  - gemfiles
  - examples
  - vendor/bundle
  - lib/sidekiq_unique_jobs/redis
  - lib/sidekiq_unique_jobs/lua
detectors:
  DuplicateMethodCall:
    exclude:
      - Sidekiq#self.use_options
      - SidekiqUniqueJobs::Lock::WhileExecuting#execute
      - SidekiqUniqueJobs::Profiler#self.stop
      - SidekiqUniqueJobs::Timing#timed
      - SidekiqUniqueJobs::Web#self.registered
      - SidekiqUniqueJobs::Locksmith#lock_sync
      - SidekiqUniqueJobs::Locksmith#wait_for_primed_token
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    enabled: true
    exclude:
      - initialize
      - Hash#slice
      - SidekiqUniqueJobs::Middleware::Client#call
      - SidekiqUniqueJobs::Script#call
      - SidekiqUniqueJobs::Script#execute
      - SidekiqUniqueJobs::Script::Caller#call_script
      - SidekiqUniqueJobs::Redis
  TooManyStatements:
    exclude:
      - initialize
      - Hash#slice
      - SidekiqUniqueJobs::Locksmith#enqueue
      - SidekiqUniqueJobs::Locksmith#wait_for_primed_token
      - SidekiqUniqueJobs::Locksmith#lock
      - SidekiqUniqueJobs::Locksmith#lock_async
      - SidekiqUniqueJobs::Locksmith#lock_sync
      - SidekiqUniqueJobs::Digests#batch_delete
      - SidekiqUniqueJobs::Digests#delete_by_pattern
      - SidekiqUniqueJobs::Lock::WhileExecuting#execute
      - SidekiqUniqueJobs::Locksmith#try_lock
      - SidekiqUniqueJobs::Profiler#self.stop
      - SidekiqUniqueJobs::Middleware#self.configure_server
      - SidekiqUniqueJobs::Middleware#with_logging_context
      - SidekiqUniqueJobs::Script#call
      - SidekiqUniqueJobs::ScriptError#generate_error_context
      - SidekiqUniqueJobs::Middleware::Client#call
      - SidekiqUniqueJobs::Middleware::Server#call
      - SidekiqUniqueJobs::UniqueArgs#filtered_args
      - SidekiqUniqueJobs::Util#del
      - SidekiqUniqueJobs::Web#self.registered
  UncommunicativeVariableName:
    exclude:
      - Hash#slice
  BooleanParameter:
    exclude:
      - SidekiqUniqueJobs::Cli#self.banner
      - SidekiqUniqueJobs::Redis
  UtilityFunction:
    enabled: false
  TooManyConstants:
    exclude:
      - SidekiqUniqueJobs
  ManualDispatch:
    enabled: true
    exclude:
      - Hash#slice
      - Hash#slice!
      - SidekiqUniqueJobs::Logging#with_configured_loggers_context
      - SidekiqUniqueJobs::Middleware#with_configured_loggers_context
      - SidekiqUniqueJobs::OnConflict::Reject#deadset_kill?
      - SidekiqUniqueJobs::SidekiqWorkerMethods#worker_method_defined?
      - SidekiqUniqueJobs::Web::Helpers#redirect_to
  MissingSafeMethod:
    exclude:
      - Array
  NilCheck:
    enabled: false
  DataClump:
    enabled: true
    exclude:
      - SidekiqUniqueJobs::Util
      - SidekiqUniqueJobs::Script
      - SidekiqUniqueJobs::Redis
  FeatureEnvy:
    exclude:
      - SidekiqUniqueJobs::Digests#batch_delete
      - SidekiqUniqueJobs::Digests#page
      - SidekiqUniqueJobs::Logging#debug_item
      - SidekiqUniqueJobs::OnConflict::Reject#push_to_deadset
      - SidekiqUniqueJobs::ScriptError#generate_error_context
      - SidekiqUniqueJobs::Util#batch_delete
      - SidekiqUniqueJobs::Web::Helpers#cparams
  InstanceVariableAssumption:
    exclude:
      - SidekiqUniqueJobs::Script::Template
  NestedIterators:
    exclude:
      - SidekiqUniqueJobs::Digests#batch_delete
      - SidekiqUniqueJobs::Locksmith#create_lock
      - SidekiqUniqueJobs::Middleware#self.configure_client
      - SidekiqUniqueJobs::Middleware#self.configure_server
      - SidekiqUniqueJobs::Util#batch_delete
      - SidekiqUniqueJobs::Util#keys_with_ttl
  RepeatedConditional:
    exclude:
      - SidekiqUniqueJobs::Locksmith
  TooManyInstanceVariables:
    exclude:
      - SidekiqUniqueJobs::Locksmith
      - SidekiqUniqueJobs::Key
  TooManyMethods:
    exclude:
      - SidekiqUniqueJobs::Locksmith
      - SidekiqUniqueJobs::Lock::BaseLock
  UncommunicativeParameterName:
    exclude:
      - SidekiqUniqueJobs::Redis
