---
exclude_paths:
  - rails_example
  - redis
  - spec
  - tmp
  - gemfiles
  - examples
detectors:
  DuplicateMethodCall:
    exclude:
    - Sidekiq#self.use_options
  IrresponsibleModule:
    exclude:
    - Sidekiq::Simulator
    - SidekiqUniqueJobs::Cli
    - SidekiqUniqueJobs::Client::Middleware
    - SidekiqUniqueJobs
    - Array
    - Hash
    - SidekiqUniqueJobs::JidMissing
    - SidekiqUniqueJobs::LockTimeout
    - SidekiqUniqueJobs::MaxLockTimeMissing
    - SidekiqUniqueJobs::RunLockFailed
    - SidekiqUniqueJobs::ScriptError
    - SidekiqUniqueJobs::UnexpectedValue
    - SidekiqUniqueJobs::UniqueKeyMissing
    - SidekiqUniqueJobs::UnknownLock
    - SidekiqUniqueJobs::Lock::BaseLock
    - SidekiqUniqueJobs::Lock::UntilAndWhileExecuting
    - SidekiqUniqueJobs::Lock::UntilExecuted
    - SidekiqUniqueJobs::Lock::UntilExecuting
    - SidekiqUniqueJobs::Lock::UntilExpired
    - SidekiqUniqueJobs::Lock::WhileExecuting
    - SidekiqUniqueJobs::Lock::WhileExecutingReject
    - SidekiqUniqueJobs::Lock::WhileExecutingRequeue
    - SidekiqUniqueJobs::Locksmith
    - SidekiqUniqueJobs::Middleware
    - SidekiqUniqueJobs::Normalizer
    - SidekiqUniqueJobs::Scripts
    - SidekiqUniqueJobs::Server::Middleware
    - Sidekiq::Job
    - Sidekiq::Job::UniqueExtension
    - Sidekiq::JobSet
    - Sidekiq::JobSet::UniqueExtension
    - Sidekiq::Queue
    - Sidekiq::Queue::UniqueExtension
    - Sidekiq::ScheduledSet
    - Sidekiq::ScheduledSet::UniqueExtension
    - Sidekiq::SortedEntry
    - Sidekiq::SortedEntry::UniqueExtension
    - Sidekiq
    - Sidekiq::Worker
    - Sidekiq::Worker::ClassMethods
    - Sidekiq::Worker::Overrides
    - Sidekiq::Worker::Overrides::Testing
    - SidekiqUniqueJobs::Timeout::Calculator
    - SidekiqUniqueJobs::Timeout
    - SidekiqUniqueJobs::Unlockable
    - SidekiqUniqueJobs::Util
  TooManyStatements:
    exclude:
    - initialize
    - Hash#slice
    - SidekiqUniqueJobs::Locksmith#create_lock
    - SidekiqUniqueJobs::Locksmith#expire_when_necessary
    - SidekiqUniqueJobs::Middleware#configure_server_middleware
    - SidekiqUniqueJobs::Server::Middleware#call
    - SidekiqUniqueJobs::UniqueArgs#filtered_args
    - SidekiqUniqueJobs::Util#del
  UncommunicativeVariableName:
    exclude:
    - Hash#slice
  BooleanParameter:
    exclude:
    - SidekiqUniqueJobs::Cli#self.banner
  UtilityFunction:
    enabled: false
  TooManyConstants:
    exclude:
    - SidekiqUniqueJobs
  ManualDispatch:
    enabled: true
    exclude:
    - Hash#slice
    - Hash#slice!
    - SidekiqUniqueJobs::Lock::WhileExecutingReject#deadset_kill?
    - SidekiqUniqueJobs::SidekiqWorkerMethods#worker_method_defined?
  MissingSafeMethod:
    exclude:
    - Array
  NilCheck:
    enabled: false
  FeatureEnvy:
    exclude:
    - SidekiqUniqueJobs::Lock::WhileExecutingReject#push_to_deadset
    - SidekiqUniqueJobs::Logging#debug_item
    - SidekiqUniqueJobs::Util#batch_delete
  NestedIterators:
    exclude:
    - SidekiqUniqueJobs::Locksmith#create_lock
    - SidekiqUniqueJobs::Middleware#configure_client_middleware
    - SidekiqUniqueJobs::Middleware#configure_server_middleware
    - SidekiqUniqueJobs::Util#batch_delete
  TooManyInstanceVariables:
    exclude:
    - SidekiqUniqueJobs::Locksmith
  TooManyMethods:
    exclude:
    - SidekiqUniqueJobs::Locksmith
