---
exclude_paths:
  - examples
  - gemfiles
  - lib/sidekiq
  - lib/sidekiq_unique_jobs/lua
  - lib/sidekiq_unique_jobs/redis
  - my_app
  - spec
  - tmp
  - vendor/bundle
detectors:
  BooleanParameter:
    exclude:
      - SidekiqUniqueJobs::Cli#self.banner
      - SidekiqUniqueJobs::Redis
      - SidekiqUniqueJobs::Lock#locked_jids
  DataClump:
    enabled: true
    exclude:
      - SidekiqUniqueJobs::DeleteOrphan
      - SidekiqUniqueJobs::Redis
      - SidekiqUniqueJobs::Script
  DuplicateMethodCall:
    exclude:
      - Sidekiq#self.use_options
      - SidekiqUniqueJobs#toggle
      - SidekiqUniqueJobs::Lock#lock
      - SidekiqUniqueJobs::Lock::WhileExecuting#execute
      - SidekiqUniqueJobs::Locksmith#lock_sync
      - SidekiqUniqueJobs::Locksmith#wait_for_primed_token
      - SidekiqUniqueJobs::Profiler#self.stop
      - SidekiqUniqueJobs::Script::Caller#extract_args
      - SidekiqUniqueJobs::Timing#timed
      - SidekiqUniqueJobs::Web#self.registered
  FeatureEnvy:
    exclude:
      - SidekiqUniqueJobs::BatchDelete#batch_delete
      - SidekiqUniqueJobs::Digests#page
      - SidekiqUniqueJobs::Logging#debug_item
      - SidekiqUniqueJobs::OnConflict::Reject#push_to_deadset
      - SidekiqUniqueJobs::ScriptError#generate_error_context
      - SidekiqUniqueJobs::Web::Helpers#cparams
  InstanceVariableAssumption:
    exclude:
      - SidekiqUniqueJobs::Script::Template
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    enabled: true
    exclude:
      - Hash#slice
      - initialize
      - SidekiqUniqueJobs::Changelog#add
      - SidekiqUniqueJobs::Middleware::Client#call
      - SidekiqUniqueJobs::Redis
      - SidekiqUniqueJobs::Script#call
      - SidekiqUniqueJobs::Script#execute
      - SidekiqUniqueJobs::Script::Caller#call_script
      - SidekiqUniqueJobs::Script::Caller#do_call
  ManualDispatch:
    enabled: true
    exclude:
      - Hash#slice
      - Hash#slice!
      - SidekiqUniqueJobs::Logging#logging_context
      - SidekiqUniqueJobs::Logging#with_configured_loggers_context
      - SidekiqUniqueJobs::Middleware#with_configured_loggers_context
      - SidekiqUniqueJobs::OnConflict::Reject#deadset_kill?
      - SidekiqUniqueJobs::SidekiqWorkerMethods#worker_method_defined?
      - SidekiqUniqueJobs::Web::Helpers#redirect_to
  MissingSafeMethod:
    exclude:
      - Array
  NilCheck:
    enabled: false
  NestedIterators:
    exclude:
      - SidekiqUniqueJobs::BatchDelete#batch_delete
      - SidekiqUniqueJobs::Changelog#entries
      - SidekiqUniqueJobs::Changelog#page
      - SidekiqUniqueJobs::Digests#page
      - SidekiqUniqueJobs::Locksmith#create_lock
      - SidekiqUniqueJobs::Middleware#self.configure_client
      - SidekiqUniqueJobs::Middleware#self.configure_server
  RepeatedConditional:
    exclude:
      - SidekiqUniqueJobs::Locksmith
  TooManyConstants:
    exclude:
      - SidekiqUniqueJobs
  TooManyStatements:
    exclude:
      - Hash#slice
      - initialize
      - SidekiqUniqueJobs::BatchDelete#batch_delete
      - SidekiqUniqueJobs::Changelog#entries
      - SidekiqUniqueJobs::Changelog#page
      - SidekiqUniqueJobs::DeleteOrphans#find_orphans
      - SidekiqUniqueJobs::Digests#page
      - SidekiqUniqueJobs::Digests#delete_by_pattern
      - SidekiqUniqueJobs::Digests#entries
      - SidekiqUniqueJobs::Lock#lock
      - SidekiqUniqueJobs::Lock::WhileExecuting#execute
      - SidekiqUniqueJobs::Locksmith#enqueue
      - SidekiqUniqueJobs::Locksmith#lock
      - SidekiqUniqueJobs::Locksmith#lock_async
      - SidekiqUniqueJobs::Locksmith#lock_sync
      - SidekiqUniqueJobs::Locksmith#try_lock
      - SidekiqUniqueJobs::Locksmith#wait_for_primed_token
      - SidekiqUniqueJobs::Logging#logging_context
      - SidekiqUniqueJobs::Middleware#self.configure_server
      - SidekiqUniqueJobs::Middleware#with_logging_context
      - SidekiqUniqueJobs::Middleware::Client#call
      - SidekiqUniqueJobs::Middleware::Server#call
      - SidekiqUniqueJobs::Profiler#self.stop
      - SidekiqUniqueJobs::Script#call
      - SidekiqUniqueJobs::Script::Caller#call_script
      - SidekiqUniqueJobs::Script::Caller#extract_args
      - SidekiqUniqueJobs::ScriptError#generate_error_context
      - SidekiqUniqueJobs::Timeout::Calculator#lock_ttl
      - SidekiqUniqueJobs::UniqueArgs#filtered_args
      - SidekiqUniqueJobs::Web#self.registered
  TooManyInstanceVariables:
    exclude:
      - SidekiqUniqueJobs::DeleteOrphans
      - SidekiqUniqueJobs::Key
      - SidekiqUniqueJobs::Locksmith
  TooManyMethods:
    exclude:
      - SidekiqUniqueJobs::Lock::BaseLock
      - SidekiqUniqueJobs::Locksmith
      - SidekiqUniqueJobs::Lock
  UncommunicativeVariableName:
    exclude:
      - Hash#slice
  UncommunicativeParameterName:
    exclude:
      - SidekiqUniqueJobs::Redis
  UtilityFunction:
    enabled: false
