AllCops:
  Include:
    - '**/Rakefile'
    - 'lib/**/*.rb'
    - 'bin/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'Gemfile.lock'
    - 'gemfiles/**/*'
  TargetRubyVersion: 2.5

Lint/HandleExceptions:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Metrics/AbcSize:
  Max: 38

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 13

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '**/spec/**/*_spec.rb'

Metrics/PerceivedComplexity:
  Max: 8

Naming/AccessorMethodName:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Naming/FileName:
  Enabled: true
  Exclude:
    - 'lib/sidekiq-unique-jobs.rb'
    - '**/Gemfile'
    - '**/Appraisals'
    - '**/*.gemspec'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses_when_complex
  AllowSafeAssignment: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
