require:
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - "**/Rakefile"
    - "**/Gemfile"
    - "*.gemspec"
    - "lib/**/*.rb"
    - "bin/**/*.rb"
    - "spec/**/*.rb"
    - "examples/**/*.rb"
    - ".simplecov"
  Exclude:
    - "Gemfile.lock"
    - "**/*.erb"
    - "gemfiles/**/*"
    - "bin/bench"

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/RaiseException: # (0.81)
  Enabled: true

Lint/SuppressedException:
  Enabled: true

Lint/StructNewOverride: # (0.81)
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Metrics/AbcSize:
  Max: 38

Metrics/CyclomaticComplexity:
  Max: 7

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 13

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "**/spec/**/*.rb"
    - "**/*.rake"
    - "Rakefile"
    - "Gemfile"
    - "*.gemspec"

Metrics/PerceivedComplexity:
  Max: 8

Naming/AccessorMethodName:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Naming/FileName:
  Enabled: true
  Exclude:
    - lib/sidekiq-unique-jobs.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: ex

Naming/MethodParameterName:
  AllowedNames:
    - ex

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - spec/unit/sidekiq_unique_jobs/sidekiq/api_spec.rb
    - spec/unit/sidekiq_unique_jobs/core_ext_spec.rb
    - spec/regression/**/*.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/FilePath:
  Enabled: true
  Exclude:
    - spec/performance/locksmith_spec.rb

RSpec/InstanceVariable:
  Exclude:
    - spec/sidekiq_unique_jobs/middleware/client/call_spec.rb
    - spec/sidekiq_unique_jobs/middleware/server/call_spec.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
  Enabled: true

RSpec/RepeatedExample:
  Exclude:
    - spec/sidekiq_unique_jobs/unique_args_spec.rb

Style/Documentation:
  Enabled: true
  Exclude:
    - "examples/**/*.rb"
    - "my_app/**/*.rb"
    - "bin/**/*.rb"
    - "lib/sidekiq_unique_jobs/testing.rb"
    - "lib/sidekiq_unique_jobs/core_ext.rb"
    - "lib/sidekiq_unique_jobs/sidekiq_unique_ext.rb"
    - "lib/sidekiq_unique_jobs/web/**/*"
    - "lib/sidekiq_unique_jobs/on_conflict.rb"
    - "lib/sidekiq_unique_jobs/timeout.rb"

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses_when_complex
  AllowSafeAssignment: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
