env:
  matrix:
    - COV=false
  global:
    - CC_TEST_REPORTER_ID=88e524e8f638efe690def7a6e2c72b1a9db5cdfa74548921b734d609a5858ee5
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
dist: bionic
sudo: required
language: ruby
cache:
  bundler: true
  directories:
     - /home/travis/.rvm/
services:
  - redis-server

before_install:
  - gem install bundler -v 2.0.2
  - >
    if [[ "${COV}" = "true" ]]; then
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
    chmod +x ./cc-test-reporter;
    fi;

before_script:
  - if [[ "${COV}" = "true" ]]; then ./cc-test-reporter before-build; fi;

script:
  - >
    if [[ "${COV}" = "true" ]]; then
    bundle exec rubocop -P;
    bundle exec reek .;
    fi;
    bundle exec rspec --require spec_helper --tag ~perf

after_script:
  - if [[ "${COV}" = "true" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi;

rvm:
  - 2.4.8

matrix:
  fast_finish: true

  exclude:
    - rvm: 2.4.8
      gemfile: gemfiles/sidekiq_6.0.gemfile
    - rvm: 2.4.8
      gemfile: gemfiles/sidekiq_develop.gemfile

  include:
    - rvm: 2.5.7
      gemfile: gemfiles/sidekiq_6.0.gemfile
    - rvm: jruby-9.2.8.0
      gemfile: gemfiles/sidekiq_6.0.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/sidekiq_develop.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/sidekiq_6.0.gemfile
      env: COV=true

gemfile:
  - gemfiles/sidekiq_4.0.gemfile
  - gemfiles/sidekiq_4.1.gemfile
  - gemfiles/sidekiq_4.2.gemfile
  - gemfiles/sidekiq_5.0.gemfile
  - gemfiles/sidekiq_5.1.gemfile
  - gemfiles/sidekiq_5.2.gemfile

notifications:
  email:
    recipients:
      - mikael@zoolutions.se
  slack:
    rooms:
      secure: B05ZUPdHrhxVnz7Mlpd5KhFH2bdE9ykFRgqLFHV3EcdyWKm85PPgbfl4cNPTFXHHhzk/5E9h5hwEXpicJYSsq6lhU8i3WesidrA+GHzrpesowTHpvtJMxIjsE1Tavug0xQs/bca72yN2t51m8UiD1scOSIuvSOCNkuKkn3+rSIo=
    on_start: never
    on_failure: always
    on_success: change
