defaults: &defaults
  encoding: unicode
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>
  username: <%= ENV.fetch('DB_USERNAME') { system("whoami") } %>
  password: <%= ENV.fetch('DB_PASSWORD') { nil } %>

development:
  <<: *defaults
  database: my_app_dev

test:
  <<: *defaults
  database: my_app_test

production:
  <<: *defaults
  database: my_app_prod

