name: Rubocop
on: [push]
jobs:
  styles:
    env:
      COV: false

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: bundle install
      - run: bin/rubocop -P
      - run: bin/reek .
