name: Test SidekiqUniqueJobs
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        ruby: [2.5, 2.6, 2.7, jruby, truffleruby]
#         ruby: [2.5, 2.6, 2.7, jruby, truffleruby]
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: bundle install
    - run: bin/rubocop -P
    - run: bin/rspec
